import {spawnSync,execFileSync} from 'node:child_process';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const node=process.execPath; const run=(file,args=[],env={})=>{const result=spawnSync(node,[file,...args],{stdio:'inherit',env:{...process.env,...env}});if(result.status!==0)process.exit(result.status??1);};
const dirty=execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(); if(dirty) { console.error('NO RELEASE: worktree must be clean before attestation generation.'); process.exit(1); }
run('scripts/check-governance-contract.mjs'); run('scripts/generate-public-data.mjs'); run('scripts/test.mjs'); run('tests/governance-gate-suite.mjs'); run('tests/semantic-gate-suite.mjs'); run('tests/release-gate-suite.mjs'); run('scripts/integrity-manifest.mjs',['--check']); run('scripts/check-external-links.mjs'); run('scripts/run-governance-gates.mjs',[],{GAL_PRE_ATTESTATION:'1'}); run('scripts/check-public-exports.mjs'); run('scripts/validate.mjs'); run('scripts/check-links.mjs');
const load=async file=>JSON.parse(await readFile(file,'utf8')); const contract=await load('protocol/governance-automation.json'); const route=await load('route-manifest.json'); const subject_commit_sha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(); const artifact_hashes={};
for(const id of contract.gate_order.filter(id=>id!=='release_governance')){const raw=await readFile(`artifacts/governance/${id.replaceAll('_','-')}.json`);artifact_hashes[id]=createHash('sha256').update(raw).digest('hex');}
const integrityRaw=await readFile('integrity/manifest.json'); const links=await load('artifacts/governance/external-links.json'); const gate_results=Object.fromEntries(contract.gate_order.map(id=>[id,'pass']));
const versions={validator:'0.1.0',schemas:'draft-2020-12+integrity-manifest',terms:'0.1.0',claims:'0.1.0',relationships:'0.1.0',evidence_standard:'EVS-001-v0.1.0',security_standard:'SSS-001-v0.1.0',release_standard:'RGS-001-v0.1.0'};
const attestation={site_release:route.site_release,data_release:route.data_release,subject_commit_sha,attestation_commit_sha:null,gal_contract:`${contract.contract_id}-v${contract.version}`,checker_version:'0.1.0',versions,attested_at:new Date().toISOString(),gate_results,blocking_violations:0,artifact_hash_algorithm:'sha256',artifact_hashes,integrity_manifest_sha256:createHash('sha256').update(integrityRaw).digest('hex'),external_link_summary:Object.fromEntries(Object.entries(Object.groupBy(links.observations,x=>x.status)).map(([key,value])=>[key,value.length])),commit_signature_status:'not_measured'};
await mkdir('governance-attestations',{recursive:true}); await writeFile(`governance-attestations/site-${route.site_release}.json`,`${JSON.stringify(attestation,null,2)}\n`); run('scripts/verify-release-attestation.mjs'); console.log(`RELEASE VERIFIED: site ${route.site_release}; commit the generated attestation in an attestation-only commit.`);
